name: EricTsai
favicon: null
layout_spectrum: 0.7052878665272146
typography_spectrum: 0.6496103384997696
title: ET View on the World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6463044153060764
  lightness: 0.986611501313746
  saturation: 0.9258329789154232
  rhythmicContrast: 0.3258653022348881
purpose: []
